version: '3.8'

services:
  db:
    image: mariadb:11
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: rest_demo
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  
  api:
    build: .
    container_name: flask_api
    restart: always
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: rootpass
      DB_NAME: rest_demo
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  db_data:

